### ISSUE TITLE
Save the next card suit.

### ISSUE THREAD

**Issue by drt2009** [IrvKalb/Object-Oriented-Python-Code#4]
You do need to save the nextCardSuite to Current Card Suit, or else you game shows 

```
Next card is: King of Spades
You got it right, it was higher
Your score is: 70

Will the next card be higher or lower than the King of Clubs?  (enter h or l):  
```

Which when you ask higher or lower you display current suit value

https://github.com/IrvKalb/Object-Oriented-Python-Code/blob/e3ed8b571b0f43a9d48e17a0615a46a78ebbcfa9/Chapter_1/HigherOrLowerProcedural.py#L78

**Comment by IrvKalb** [comment]
Thank you very much for your message.  You are absolutely correct!

I've had this code this way for years, and I never noticed this error.  (And none of my students have ever pointed it out.)  I've fixed the code and uploaded the updated version.

Please let me know if you find any other errors.

I hope you enjoy the rest of the book.

Irv
