### ISSUE TITLE
HigherOrLowerProcedural.py has an incorrect comment

### ISSUE THREAD

**Issue by rogfrich** [IrvKalb/Object-Oriented-Python-Code#7]
Hi, this is about as minor as it gets, but in case it's useful...

The comment in line 11 of `HigherOrLowerProcedural.py` states that the function `getCard` returns a random card. This doesn't seem to be true - it returns the first card in the list, or the "top" one. 

```python
# Pass in a deck and this function returns a random card from the deck
def getCard(deckListIn):
    thisCard = deckListIn.pop() # pops one off the top of the deck and returns it
    return thisCard
```

Thanks from a happy reader!

**Comment by IrvKalb** [comment]
Technically, you are correct.  The implementation is that the cards are already randomized (shuffled). 

However, the function is doing exactly what the comment says, it is returning a random card from the deck.

**Comment by rmbhub** [comment]
hi,  Thank you for the wonderful python object-oriented book.But I was a little confused when I tried to practice the code in chapter 1.
We always take cards from the top, not the bottom
I think it's more appropriate to use **pop(0)** in code,

when the code run **pop()**,  the pointer is always placed in the last position, The next card will always be **NULL**;
If i take a card from the top with **pop(0)**, next is the top card, as described in the original book.
